### ISSUE TITLE
Validate structured navigation content against a JSON schema

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/StructuredNavigation#1]

**Comment by SamanthaNguyen** [comment]
To note: the provided JSON schema in the repository source code actually works now. It was added in https://github.com/SamanthaNguyen/mediawiki-extensions-StructuredNavigation/commit/e143c7a7fa30a552ce090405f6ad33aae62d085f and now fully works properly as of https://github.com/SamanthaNguyen/mediawiki-extensions-StructuredNavigation/commit/041925494c037dd280be04249a4440afc858a317.

To test this out:
1. Visit https://www.jsonschemavalidator.net/
2. Paste the [schema](https://github.com/SamanthaNguyen/mediawiki-extensions-StructuredNavigation/blob/master/docs/schema/schema.v1.json) on to the left
3. Choose any of the samples under [`docs/examples`](https://github.com/SamanthaNguyen/mediawiki-extensions-StructuredNavigation/tree/master/docs/examples) and paste it onto the right

**Comment by SamanthaNguyen** [comment]
| Library                   | License    | Supported Schemas | Error Messages?                                     |
|---------------------------|------------|-------------------|-----------------------------------------------------|
| swaggest/php-json-schema  | MIT        | Draft 4, 6, 7     | Yes, but written in non-UX friendly manner          |
| justinrainbow/json-schema | MIT        | Draft 4, ???      | Yes, but not localized by default (just in English) |
| opis/json-schema          | Apache 2.0 | Draft 6, 7        | No(?)                                               |
