### ISSUE TITLE
Allow converting a wikitext-based navigation to a structured navigation (and back)

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/StructuredNavigation#12]
It should be easy for a wiki community to be able to easily transition from their wikitext, template-based navigations to structured navigations right when the extension is installed. This needs to be well-thought out and well-written in order for this migration feature to be easily maintainable.

## Base criteria
 - [ ] The wikitext-JSON codec should be in its own backend that's shared between maintenance script and special page, not hard-coded and duplicated
 - [ ] Wikitext-JSON codec shouldn't end up being a huge monster like the `\Parser` class in core

## Initial criteria
- [ ] Be able to perform wikitext-to-JSON conversion
- [ ] Be able to do migration via maintenance script
- [ ] Should be able to pass configuration options for reading a navigation template:
  - [ ] Prefix for group parameter
  - [ ] Prefix for content parameter
  - [ ] Max possible groups
  - [ ] title page parameter
  - [ ] title label parameter
  - [ ] array of separator symbols to check against (wikis tend to be inconsistent about what symbol to use)

## Post criteria
After initial criteria has been met, these need to be done as well. They're essentially the "nice to have" features but would be required for a *well* supported migration process all-around.
- [ ] Be able to perform JSON-to-wikitext conversion as well (for when a wiki wants to uninstall the extension)
- [ ] Be able to do migration via special page (for system administrators that don't have backend access)
  - [ ] First, this needs some UI mockups/concepts for figuring out what the form would look like
  - [ ] Needs to use `\HTMLForm`; don't reinvent the wheel!
    - [ ] If this ends up needing any custom form fields, one should be written by extending `\HTMLFormField`

**Comment by SamanthaNguyen** [comment]
Process for wikitext-to-JSON would look something like:

1. Get list of all navigation templates either by:
   - under specified category of interest by user (e.g get all template titles under `[[Category:Navigation templates]]`), or...
   - manual list of templates titles separated by newline
2. Read and parse the content of the specified template (e.g `[[Template:Bionicle/Sets/2016]]`)
4. **Make edit**: Create title under Navigation namespace with same title (`Navigation:Bionicle/Sets/2016]]`)
5. **Make edit**: Replace template content with specified title (`<mw-navigation title="Bionicle/Sets/2016">`)

Each edit should be marked as a **bot edit**, but not a minor edit. It'd probably be useful to log this conversion to `Special:Log` too.
