### ISSUE TITLE
Allow customizing a view of a page in the Navigation namespace

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/StructuredNavigation#13]
A user should be able to customize the view of a page in the Navigation namespace, with the following options:
 - JSON as formatted table
 - an HTML-rendered navigation
 - pure source-code (like seen in CSS and JS pages)

**Comment by SamanthaNguyen** [comment]
Partially done with https://github.com/SamanthaNguyen/mediawiki-extensions-StructuredNavigation/commit/43bcee93dbff3549cf2bf44131254fa1620f2cd9
