### ISSUE TITLE
Navigations should be able to be collapsible

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/StructuredNavigation#30]
**Is your feature request related to a problem? Please describe.**
The content of a navigation shouldn't necessarily have to be automatically visible

**Describe the solution you'd like**
A user would be allowed to pass these two attributes.
 - `is-collapsible`: Attribute that defines whether or not it can be collapsed. This would add `mw-collapsible` as a class
 - `is-collapsed`: Attribute that defines whether or not the default state of the navigation is collapsed. This would add `mw-collapsed` as a class

**Describe alternatives you've considered** N/A

**Additional context**
- http://mediawiki.org/wiki/Manual:Collapsible_elements

**Comment by SamanthaNguyen** [comment]
Will make a patch tomorrow. This will support two new attributes to the extension-registered parser tag:
- `is-collapsible`: Attribute that defines whether or not it can be collapsed
- `is-collapsed`: Attribute that defines whether or not the default state of the navigation is collapsed
