### ISSUE TITLE
Investigate: Ways to improve performance

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/StructuredNavigation#31]
Mainly just questions to see if there are areas that need improvements on performance.

## ResourceLoader
   - [ ] Does a ResourceLoader module get loaded twice if you have two instances of a parser tag on the same page?
   - [ ] Should probably curate the ResourceLoader modules. Right now, the navigation style and separator style are separated because there should not be a delay in loading CSS styles of the actual navigation, which are considered the higher-priority styles. By merging them, there would be a delay in loading (I've tested this). Would it be worth merging for performance, despite a style-loading delay?

## Retrieving content 
 - [ ] Does the JSON content retrieval need to be done through a queued job or deferred update? Does this extension need it's own layer of caching, and then have the extension retrieve the content from the cache storage if and when possible?

 # OOUI loading
 - [x] This extension uses OOUI for pure dynamic HTML generation (generating unordered lists and description lists). However this requires calling `$parser->enableOOUI()`, which loads some modules that don't get used. How can we enable OOUI without having performance degraded? **Edit**: This was fixed 
in cea3c79 👏

**Comment by SamanthaNguyen** [comment]
The task and summary has been modified to cover more performance-related areas that could be investigated into.

**Comment by SamanthaNguyen** [comment]
After giving it some thought, it'd be better to have the JSON content of a navigation be retrieved through a job versus a deferred update, since a navigation's content probably won't be changed that often and thus would be considered "non-urgent".

**Comment by SamanthaNguyen** [comment]
Just to make sure, going to research that a queued job is the right direction and implementation for this hopefully sometime this week

**Comment by SamanthaNguyen** [comment]
Micro-optimization patch (was also done for readability/preference): https://github.com/SamanthaNguyen/mediawiki-extensions-StructuredNavigation/commit/3ce8a57551cad865b96f40a17de0fb21f025b6c4
