### ISSUE TITLE
Investigate: Storing structured navigation data in the database

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/StructuredNavigation#39]
This would be a large undertaking. Does this make sense to do?

There is native JSON support in MariaDB 10.2 as well as MySQL 5.7.

MariaDB refs:
- https://mariadb.com/resources/blog/json-with-mariadb-10-2/
- https://mariadb.com/kb/en/library/json-data-type/
- https://mariadb.com/kb/en/library/json-functions/

MySQL refs:
- https://dev.mysql.com/doc/refman/5.7/en/json.html
- https://dev.mysql.com/doc/refman/5.7/en/json-function-reference.html

**Comment by SamanthaNguyen** [comment]
There’s SQLite support for this but unfortunately it’s in the form of an extension ( https://www.sqlite.org/json1.html; also https://dba.stackexchange.com/questions/122198/is-it-possible-to-store-and-query-json-in-sqlite ). This extension isn’t “bundled” by default AFAIK: ideally we wouldn’t have to require those running a MW instance on SQLite to install an SQLite extension.

Note that of course MediaWiki officially supports MySQL/MariaDB as the de-facto DB management system to use, while SQLite has less mature support. 

DB supported versions as of MW 1.32 (latest stable version):
- MySQL 5.5.8+
- PostgreSQL 9.2+
- SQLite 3.3.7+
- Oracle 9.0.1+
- Microsoft SQL Server 2005 (9.00.1399)

If development does start, I would plan to start just supporting MySQL/MariaDB. (I'd be fine with supporting SQLite but that probably wouldn't come in unless if there were more discussion plus a patch to go with it)
