### ISSUE TITLE
Investigate: Integration with VisualEditor extension for inserting a structured navigation into a page

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/StructuredNavigation#42]
**Is your feature request related to a problem? Please describe.**
As a user, I would like a visual way to insert a structured navigation into a wikitext page.

**Describe the solution you'd like**
This extension should provide integration with the VisualEditor extension for inserting a structured navigation.

Process would go like this:
1. The toolbar group that says "Insert" is tapped
2. The "Structured navigation" option will appear inside the toolbar dropdown-menu, and is tapped
3. An OOUI dialog pops up with two text input field:
   - one for searching for the title in the `NS_NAVIGATION` namespace (TitleInputWidget)
   - and another regular text field widget that's optional, for adding an ID attribute
4. The dialog form is filled out and the "Insert" button on the dialog is tapped
5. The structured navigation is inserted to the page and the user saves their edit

**Describe alternatives you've considered** N/A

**Additional context**
There are other extensions that provide this VE integration. Should look at these other extensions as an example:
 - [Cite](https://github.com/wikimedia/mediawiki-extensions-Cite/tree/master/modules/ve-cite)
 - [Graph](https://github.com/wikimedia/mediawiki-extensions-Graph/tree/master/modules/ve-graph)
 - [Kartographer](https://github.com/wikimedia/mediawiki-extensions-Kartographer/tree/master/modules/ve-maps)
 - [Math](https://github.com/wikimedia/mediawiki-extensions-Math/tree/master/modules/ve-math)
 - [Score](https://github.com/wikimedia/mediawiki-extensions-Score/tree/master/modules/ve-score)
 - [WikiHiero](https://github.com/wikimedia/mediawiki-extensions-wikihiero/tree/master/modules/ve-wikihiero)

**Comment by SamanthaNguyen** [comment]
Note: For registering RL modules for VisualEditor, first register the module in ResourceModules, and then register in VisualEditorPluginModules in extension.json

**Comment by SamanthaNguyen** [comment]
Relevant documentation:

 - DataModel node:
   - https://doc.wikimedia.org/VisualEditor/master/#!/api/ve.dm.MWBlockExtensionNode
   - https://doc.wikimedia.org/VisualEditor/master/#!/api/ve.dm.MWInlineExtensionNode
 - ContentEditable nodes:
   - https://doc.wikimedia.org/VisualEditor/master/#!/api/ve.ce.MWBlockExtensionNode
   - https://doc.wikimedia.org/VisualEditor/master/#!/api/ve.ce.MWInlineExtensionNode
- Inspector-related objects
  - https://doc.wikimedia.org/VisualEditor/master/#!/api/ve.ui.MWExtensionInspector
    - https://doc.wikimedia.org/VisualEditor/master/#!/api/ve.ui.MWLiveExtensionInspector
  - https://doc.wikimedia.org/VisualEditor/master/#!/api/ve.ui.FragmentInspectorTool

**Comment by SamanthaNguyen** [comment]
Currently have Parsoid and VE working (mostly) since yesterday:
![image](https://user-images.githubusercontent.com/4723983/52180409-4ad6e900-27ab-11e9-87d7-d1fb85391422.png)

Just need to figure out why the "Structured navigation" option isn't showing up. Once that's fixed, this feature will be merged into master 💯 🔥
