### ISSUE TITLE
Allow users to view examples of navigation JSON on-wiki

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/StructuredNavigation#46]
**Is your feature request related to a problem? Please describe.**
As a user, I'd like to be able to understand how the extension works and how the specific content to StructuredNavigation is written to be able to create structured navigation.

**Describe the solution you'd like**
The extension should provide content bundled with the actual source code. This currently does happen, but to a different extent: they just exist in the `/docs/examples` folder. I'd like to be able to bundle content that would be able to be viewed directly on-wiki.

Acceptance criteria
 - [ ] Provide a maintenance script for CLI usage
 - [ ] Provide a special page which provides a specialized user interface
    - [ ] This special page is protected by a user right
 - [ ] Allow choosing which ones can be imported
 - [ ] Documentation is provided under docs/extension for the maintenance script **and** special page

**Describe alternatives you've considered** N/A
**Additional context** N / A

**Comment by SamanthaNguyen** [comment]
Progress:
![image](https://user-images.githubusercontent.com/4723983/53295879-7a857980-37ca-11e9-9f97-a74a3f1ed440.png)

**Comment by SamanthaNguyen** [comment]
Nice-to-have: Feature to add selected examples to watchlist after they're imported. It would be a checkbox option that says "Add selected pages to watchlist"/"Watch selected pages"; this would be good for a future task
