### ISSUE TITLE
Implement a visual editor interface for editing and creating structured navigations

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/StructuredNavigation#8]

**Comment by SamanthaNguyen** [comment]
Next feature coming up

**Comment by SamanthaNguyen** [comment]
Progress:

![image](https://user-images.githubusercontent.com/4723983/60147854-9149d600-9794-11e9-9434-838bd4074576.png)
Uses a BookletLayout (OOUI component), which allows paged tabbing. The title allows entering the name of the navigation.

The "Groups" page allows entering the links of the navigation. This is how it'll work:
* Pressing "add another" will add another row of this, to make another link.
* Pressing the trash icon will delete the row itself. 
* The "title" input is a TitleInputWidget, which will give search suggestions based on existing titles.
* The "label" input is a free-form TextInputWidget.

Things to work out:
* There should be a "Preview" page, which will render the navigation. Might need to create a client-side version of the NavigationView component, and a client-side version of JsonEntity
